version: 2.1

orbs:
  rok8s-scripts: fairwinds/rok8s-scripts@9.2.0

references:
  install_goreleaser: &install_goreleaser
    run:
      name: Install GoReleaser
      command: |
        curl -fsSLo goreleaser.deb https://github.com/goreleaser/goreleaser/releases/download/v0.119.0/goreleaser_amd64.deb
        echo "e4552d00d8448c4da5f2044e0ad8ba49bcd636502b4799751e16341d5e235d24 goreleaser.deb" | sha256sum -c
        sudo dpkg -i goreleaser.deb

  docker_build_and_push: &docker_build_and_push
    run:
      name: Docker login, build, and push
      command: |
        docker build -f Dockerfile -t quay.io/reactiveops/rbac-manager:$DOCKER_BASE_TAG .

        if [[ -z $CIRCLE_PR_NUMBER ]]; then
          bash <(curl -s https://codecov.io/bash)
          docker login quay.io -u="reactiveops+circleci" -p="${quay_token}"
          docker push quay.io/reactiveops/rbac-manager:$DOCKER_BASE_TAG

        else
          echo "Skipping push for forked PR"
        fi

jobs:
  test:
    docker:
      - image: circleci/golang:1.12-stretch
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
      - run: golangci-lint run
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)

  build:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker
      - run: echo 'export DOCKER_BASE_TAG=dev-$CIRCLE_SHA1' >> $BASH_ENV
      - *docker_build_and_push

  release:
    docker:
      - image: circleci/buildpack-deps:jessie
    steps:
      - checkout
      - setup_remote_docker
      - run: echo 'export DOCKER_BASE_TAG=$CIRCLE_TAG' >> $BASH_ENV
      - *docker_build_and_push


workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          context: org-global
  release:
    jobs:
      - release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^testing-.*/
